[package]
name = "ffrelay-api"
version.workspace = true
edition.workspace = true

[dependencies]
bon.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tabled.workspace = true
thiserror.workspace = true
